# Setup
title:               티끌 모아 태산
tagline:             "yunvo's unregulated logs!"
description:         '<img class="fit-picture" src="https://cdn.pixabay.com/photo/2017/11/14/13/06/kitty-2948404_1280.jpg">'
url:                 https://yunvo.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Kim Yunvo
  url:               https://github.com/yunvo
  email:             kimyn1331.k@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
# version:             1.1.0
google_analytics_id: #UA-XXXX-Y

github:
  repo:              https://github.com/yunvo

category_dir: category/
tag_dir: tag/
